#!/bin/bash
# ============================================================
# install.sh — One-liner git_sync installer (Linux & macOS)
# Usage:
#   curl -sSL http://YOUR_IP:8090/install.sh | bash
#   curl -sSL http://YOUR_IP:8090/install.sh | bash -s -- https://github.com/user/repo.git
# ============================================================

set -e

# ── Config ───────────────────────────────────────────────────
REPO_URL="${1:-https://github.com/Roshan-yadav-evil-genius/TheOneEye.git}"
# ─────────────────────────────────────────────────────────────

REPO_NAME=$(basename "$REPO_URL" .git)
INSTALL_DIR="$HOME/.git_sync"
SYNC_SCRIPT="$INSTALL_DIR/git_sync.sh"
LOG_FILE="$HOME/.git_sync.log"
CRON_TAG="# git_sync_hourly"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
info() { echo -e "${CYAN}[→]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

echo ""
echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}   git_sync Installer — Linux / macOS      ${NC}"
echo -e "${CYAN}============================================${NC}"
echo ""

# ── 1. Detect OS ─────────────────────────────────────────────
if [[ "$OSTYPE" == "darwin"* ]]; then
    DESKTOP="$HOME/Desktop"
    OS="macOS"
else
    DESKTOP="${XDG_DESKTOP_DIR:-$HOME/Desktop}"
    OS="Linux"
fi
ok "Detected: $OS"

# ── 2. Check git ─────────────────────────────────────────────
command -v git &>/dev/null || err "git not installed. Please install git first."
ok "git: $(git --version)"

# ── 3. Check crontab ─────────────────────────────────────────
command -v crontab &>/dev/null || err "crontab not found. Install cron: sudo apt install cron"
ok "crontab available"

# ── 4. Create install dir ────────────────────────────────────
mkdir -p "$INSTALL_DIR"
ok "Install dir: $INSTALL_DIR"

# ── 5. Write sync script ─────────────────────────────────────
info "Writing sync script to $SYNC_SCRIPT ..."

cat > "$SYNC_SCRIPT" << 'ENDSYNC'
#!/bin/bash
# Auto-generated by install.sh
REPO_URL="__REPO_URL__"
REPO_NAME=$(basename "$REPO_URL" .git)
if [[ "$OSTYPE" == "darwin"* ]]; then
    DESKTOP="$HOME/Desktop"
else
    DESKTOP="${XDG_DESKTOP_DIR:-$HOME/Desktop}"
fi
REPO_DIR="$DESKTOP/$REPO_NAME"
LOG_FILE="$HOME/.git_sync.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"; }

log "---------- git_sync started ----------"
log "Repo: $REPO_URL"
log "Target: $REPO_DIR"

command -v git &>/dev/null || { log "ERROR: git not found"; exit 1; }
mkdir -p "$DESKTOP"

if [ -d "$REPO_DIR/.git" ]; then
    log "Repo exists — running git pull..."
    cd "$REPO_DIR" && OUTPUT=$(git pull 2>&1); STATUS=$?
    log "$OUTPUT"
    [ $STATUS -eq 0 ] && log "git pull succeeded." || log "ERROR: git pull failed (code $STATUS)."
else
    log "Repo missing — running git clone..."
    OUTPUT=$(git clone "$REPO_URL" "$REPO_DIR" 2>&1); STATUS=$?
    log "$OUTPUT"
    [ $STATUS -eq 0 ] && log "git clone succeeded." || log "ERROR: git clone failed (code $STATUS)."
fi
log "---------- git_sync finished ----------"
ENDSYNC

# Substitute the repo URL into the script
sed -i.bak "s|__REPO_URL__|$REPO_URL|g" "$SYNC_SCRIPT" && rm -f "$SYNC_SCRIPT.bak"
chmod +x "$SYNC_SCRIPT"
ok "Sync script written"

# ── 6. Register hourly cron ──────────────────────────────────
info "Registering cron job..."
EXISTING=$(crontab -l 2>/dev/null || true)
CLEANED=$(echo "$EXISTING" | grep -v "$CRON_TAG" || true)
NEW_LINE="0 * * * * \"$SYNC_SCRIPT\" >> \"$LOG_FILE\" 2>&1 $CRON_TAG"
( echo "$CLEANED"; echo "$NEW_LINE" ) | grep -v '^$' | crontab -
ok "Cron registered: every hour at :00"

# ── 7. Run immediately ───────────────────────────────────────
echo ""
info "Running sync now (first time)..."
echo "--------------------------------------------"
bash "$SYNC_SCRIPT"
echo "--------------------------------------------"

# ── 8. Done ──────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}   All done!${NC}"
echo -e "${GREEN}============================================${NC}"
printf "  %-12s %s\n" "Repo:"    "$REPO_URL"
printf "  %-12s %s\n" "Cloned to:" "$DESKTOP/$REPO_NAME"
printf "  %-12s %s\n" "Script:"  "$SYNC_SCRIPT"
printf "  %-12s %s\n" "Logs:"    "$LOG_FILE"
printf "  %-12s %s\n" "Schedule:" "Every hour at :00 (cron)"
echo ""
echo -e "  ${YELLOW}View logs :${NC} tail -f $LOG_FILE"
echo -e "  ${YELLOW}Uninstall :${NC} crontab -l | grep -v '$CRON_TAG' | crontab - && rm -rf $INSTALL_DIR"
echo -e "${GREEN}============================================${NC}"
echo ""
