# ============================================================
# install.ps1 — One-liner git_sync installer (Windows)
# Usage (PowerShell as Admin):
#   irm http://YOUR_IP:8090/install.ps1 | iex
# Or with custom repo:
#   $env:REPO_URL="https://github.com/user/repo.git"; irm http://YOUR_IP:8090/install.ps1 | iex
# ============================================================

$ErrorActionPreference = "Stop"

# ── Config ───────────────────────────────────────────────────
$REPO_URL   = if ($env:REPO_URL) { $env:REPO_URL } else { "https://github.com/YOUR_USERNAME/YOUR_REPO.git" }
# ─────────────────────────────────────────────────────────────

$REPO_NAME   = [System.IO.Path]::GetFileNameWithoutExtension($REPO_URL)
$INSTALL_DIR = "$env:USERPROFILE\.git_sync"
$SYNC_SCRIPT = "$INSTALL_DIR\git_sync.ps1"
$LOG_FILE    = "$env:USERPROFILE\.git_sync.log"
$TASK_NAME   = "GitSyncHourly"
$DESKTOP     = "$env:USERPROFILE\Desktop"
$REPO_DIR    = "$DESKTOP\$REPO_NAME"

function Write-OK   { param($msg) Write-Host "[OK] $msg"    -ForegroundColor Green  }
function Write-Info { param($msg) Write-Host " ->  $msg"    -ForegroundColor Cyan   }
function Write-Warn { param($msg) Write-Host "[!]  $msg"    -ForegroundColor Yellow }
function Write-Err  { param($msg) Write-Host "[ERR] $msg"   -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "   git_sync Installer - Windows             " -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check git ─────────────────────────────────────────────
try {
    $gitVer = & git --version 2>&1
    Write-OK "git found: $gitVer"
} catch {
    Write-Err "git is not installed. Download from: https://git-scm.com/download/win"
}

# ── 2. Create install dir ────────────────────────────────────
if (-not (Test-Path $INSTALL_DIR)) { New-Item -ItemType Directory -Path $INSTALL_DIR | Out-Null }
Write-OK "Install dir: $INSTALL_DIR"

# ── 3. Write sync script ─────────────────────────────────────
Write-Info "Writing sync script to $SYNC_SCRIPT ..."

$syncContent = @"
# Auto-generated by install.ps1 — do not edit manually
`$REPO_URL  = "$REPO_URL"
`$REPO_NAME = [System.IO.Path]::GetFileNameWithoutExtension(`$REPO_URL)
`$DESKTOP   = "`$env:USERPROFILE\Desktop"
`$REPO_DIR  = "`$DESKTOP\`$REPO_NAME"
`$LOG_FILE  = "`$env:USERPROFILE\.git_sync.log"

function Log { param(`$msg) `$ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'; `$line = "[`$ts] `$msg"; Add-Content -Path `$LOG_FILE -Value `$line; Write-Host `$line }

Log "---------- git_sync started ----------"
Log "Repo: `$REPO_URL"
Log "Target: `$REPO_DIR"

if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Log "ERROR: git not found"; exit 1 }
if (-not (Test-Path `$DESKTOP)) { New-Item -ItemType Directory -Path `$DESKTOP | Out-Null }

if (Test-Path "`$REPO_DIR\.git") {
    Log "Repo exists - running git pull..."
    Set-Location `$REPO_DIR
    `$out = & git pull 2>&1 | Out-String
    Log `$out
    if (`$LASTEXITCODE -eq 0) { Log "git pull succeeded." } else { Log "ERROR: git pull failed (code `$LASTEXITCODE)." }
} else {
    Log "Repo missing - running git clone..."
    `$out = & git clone `$REPO_URL `$REPO_DIR 2>&1 | Out-String
    Log `$out
    if (`$LASTEXITCODE -eq 0) { Log "git clone succeeded." } else { Log "ERROR: git clone failed (code `$LASTEXITCODE)." }
}
Log "---------- git_sync finished ----------"
"@

Set-Content -Path $SYNC_SCRIPT -Value $syncContent -Encoding UTF8
Write-OK "Sync script written"

# ── 4. Register Task Scheduler job ───────────────────────────
Write-Info "Registering Task Scheduler job: $TASK_NAME ..."

# Remove old task if exists
$existingTask = Get-ScheduledTask -TaskName $TASK_NAME -ErrorAction SilentlyContinue
if ($existingTask) {
    Unregister-ScheduledTask -TaskName $TASK_NAME -Confirm:$false
    Write-Warn "Removed existing task."
}

try {
    $action  = New-ScheduledTaskAction -Execute "powershell.exe" `
                 -Argument "-NonInteractive -WindowStyle Hidden -File `"$SYNC_SCRIPT`""
    $trigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 1) `
                 -Once -At (Get-Date)
    $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
                  -StartWhenAvailable
    Register-ScheduledTask -TaskName $TASK_NAME -Action $action `
      -Trigger $trigger -Settings $settings -RunLevel Highest -Force | Out-Null
    Write-OK "Task Scheduler job registered: every 1 hour"
} catch {
    Write-Warn "Could not register task (try running as Administrator)."
    Write-Warn "Manual command: schtasks /create /tn $TASK_NAME /tr `"powershell -File '$SYNC_SCRIPT'`" /sc HOURLY"
}

# ── 5. Run immediately ───────────────────────────────────────
Write-Host ""
Write-Info "Running sync now (first time)..."
Write-Host "--------------------------------------------"
& powershell -NonInteractive -File $SYNC_SCRIPT
Write-Host "--------------------------------------------"

# ── 6. Done ──────────────────────────────────────────────────
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "   All done!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ("  {0,-12} {1}" -f "Repo:",     $REPO_URL)
Write-Host ("  {0,-12} {1}" -f "Cloned to:", $REPO_DIR)
Write-Host ("  {0,-12} {1}" -f "Script:",   $SYNC_SCRIPT)
Write-Host ("  {0,-12} {1}" -f "Logs:",     $LOG_FILE)
Write-Host ("  {0,-12} {1}" -f "Schedule:", "Every 1 hour (Task Scheduler)")
Write-Host ""
Write-Host "  View logs  : Get-Content $LOG_FILE -Wait" -ForegroundColor Yellow
Write-Host "  Manage     : taskschd.msc" -ForegroundColor Yellow
Write-Host "  Uninstall  : Unregister-ScheduledTask -TaskName $TASK_NAME -Confirm:`$false" -ForegroundColor Yellow
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
